services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=employee_review_db
      - POSTGRES_USER=employee_review_user
      - POSTGRES_PASSWORD=employee_review_password
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    environment:
      - DB_NAME=employee_review_db
      - DB_USER=employee_review_user
      - DB_PASSWORD=employee_review_password
      - DB_HOST=db
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  postgres_data:
